In [1]:
a = ['a','c','r','g','y']
s = ' '.join(a)

In [15]:
a = ['hari','krishna', 'hari']
for i,j,k in enumerate(a):
    print(i, j, k)

ValueError: not enough values to unpack (expected 3, got 2)

# reverse of the number

In [18]:
n = int(input())
rev = 0
while(n>0):
    r = n%10
    rev = rev *10 +r
    n = n//10
    print(rev)

123
3
32
321


In [ ]:
n = int(input())
rev = 0
while(n>0):
    r = n%10
    rev = rev*10 +r
    n = n//10
print(rev)
    

# sum of the digit of the numbers

In [25]:
n = input()
l = []
for i in (i)
    l.append(k)
sum(l)n:
    k = int


123


6

In [27]:
n = int(input())
su = 0
while(n>0):
    r = n%10
    su = su + r
    n = n//10
print(su)

123
6


# check the num palindrome or not

In [30]:
n = input()
k = n[::-1]
if n== k:
    print(' it is palindrome')
else:
    print(' it is not palindrome')

133
 it is not palindrome


In [42]:
n = int(input())
temp = n
rev = 0
l = []
while (n>0):
    r = n %10
    rev = rev *10 + r
    n = n//10
if(temp == rev):
    print('it is palindrome')
else:
    print('it is not palindrome')

121
it is palindrome


# average of numbers in a list

In [43]:
n = int(input())
l = []
for i in range(n):
    k = int(input())
    l.append(k)
avg = sum(l)/n
print(avg)
    

3
12
35
52
33.0


# count the number in digits

In [44]:
n = int(input())
count = 0
while(n>0):
    count = count +1
    n = n//10
print(count)

123
3


# table

In [48]:
n = int(input())
for i in range(1,11):
    print(n,'x',i,'=',i*n)

7
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


# prime no or not

In [4]:
strt = int(input())
end = int(input())
for i in range(strt, end+1):
    if i>1:
        for j in range(2,i):
            if (i %j ==0):
                break
        else:
            print(i)

11
30
11
13
17
19
23
29


In [ ]:
fro i in range(1,0):
    if i = 0:
        for j in range(2,i):
            if (i%j == 0):
                break
        else:
            print(i)

In [6]:
n = int(input())
for i in range(1,n):
    if i>1:
        for j in range(2,i):
            if i%j == 0:
                break
        else:
            print(i)

20
2
3
5
7
11
13
17
19


In [8]:
n = int(input())
k = 0
for i in range(2,n//2+1):
    if (n%i ==0):
        k = k +1
if k<=0:
    print('num is prime')
else:
    print('it is not prime')

3
num is prime


# check amstrong num

In [11]:
n = int(input())
temp = n
amg = 0
while n>0:
    r = n%10
    amg = amg + pow(r,3)
    n = n//10
if temp == amg:
    print(' it is amstrng')
else:
    print('it is not amstrng')

372
it is not amstrng


# check num perfect or not

In [15]:
n = int(input())
temp = n
c = 0
for i in range(1, n):
    if n%i== 0:
        c = c+i
if c == temp:
    print('it is perfrct num')
else:
    print('it is not perfect num')
        

6
it is perfrct num


In [17]:
n = int(input())
temp = n
c = 0
for i in range(1,n):
    if n%i ==0:
        c = c+i
if c == temp:
    print('it is perfect num')
else:
    print('it is not perfect num')

6
it is perfect num


# coding ninjas

In [24]:
n = input()
l = [i for i in n]
from collections import Counter
a = Counter(l)
print(a.keys())

AAARREKR
dict_keys(['A', 'R', 'E', 'K'])


# reverse of the word

In [29]:
n = input().split()
l = []
for i in n:
    k = i[::-1]
    l.append(k)
l

i am hari krishna


['i', 'ma', 'irah', 'anhsirk']

In [32]:
s = ' '.join(l)
print(s)

i ma irah anhsirk


# highest occuring chr

In [38]:
from collections import Counter
n = input()
l = [i for i in n]
d = Counter(l)
k = max(d.values())
for key, value in d.items():
    if value == k:
        a = key
print(a)
        

ketjtje\
j


In [40]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
for i in np.nditer(y):
    print(i)

1
2
3
4
5
6
7
8
9


In [45]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.eye(3,6,0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [56]:
a = np.zeros((8,8))
a[1:7,1:7] = 1

In [57]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])