In [12]:
import numpy as np
a = np.array([1,2,3])

In [13]:
a

array([1, 2, 3])

In [14]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


## NUMPY ARRAYS ARE FASTER THAN LIST BECOUSE THEY ARE DENSILY PACKED IN MEMORY

In [15]:
a.ndim 

1

In [16]:
b.ndim

2

In [17]:
a.shape

(3,)

In [18]:
b.shape

(2, 3)

In [19]:
a.size

3

In [20]:
b.size

6

In [21]:
a.dtype

dtype('int32')

In [22]:
b.dtype

dtype('int32')

In [23]:
a.itemsize

4

In [24]:
b.itemsize

4

In [25]:
a.data

In [26]:
b.data

# NUMPY.EMPTY

In [41]:
x = np.empty([3,2], dtype = int)
x
#NOTE: it will show random values

array([[494910160,       444],
       [        0,         0],
       [   131074,   5242972]])

In [42]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [44]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [45]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [49]:
x = np.linspace(10,20,9)
x

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [50]:
x = np.logspace(1.0,2.0,num = 10)
print(x)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [51]:
a = np.random.randn(2)
print(a)

[-0.47279842  1.821667  ]


In [54]:
arr = np.array([1,2,3,4])
print(arr[0])
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0][1])

1
2


In [60]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9],[6,7,8]]])
print(arr[0][1][2])

7


In [61]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])

8


In [62]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]


# # COPY VS VIEW    IMPORTANT

In [69]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [67]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [70]:
arr = np.array([1,2,3,4])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4]


In [75]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narr = arr.reshape(4,3)
print(narr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [78]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narr = arr.reshape(2,3,2)
print(narr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [106]:
arr =  np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narr = arr.reshape(3,-1)
print(narr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# flattening the array:

In [109]:
arr = np.array([[1,2,3],[4,5,6]])
nrr = arr.reshape(-1)
print(nrr)

[1 2 3 4 5 6]


In [111]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())
print(arr.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [117]:
arr = np.array([[1,2,3],[4,5,6]])
a = arr.flatten()
a[2] = 50
print(a)

[ 1  2 50  4  5  6]


In [118]:
arr = np.array([[1,2,3],[4,5,6]])
a = arr.ravel()
a[2] = 50
print(a)

[ 1  2 50  4  5  6]


# iterating arrays using nditer():
    

In [182]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# ndenumerate

In [125]:
arr = np.array([[1,2,3],[4,5,6]])
for x in np.ndenumerate(arr):
    print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)


# NUMPY JOIN

In [129]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [131]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
c = np.concatenate((a,b), axis = 0)
print(c)
c = np.concatenate((a,b), axis = 1)
print(c)



[[1 2]
 [3 4]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [3 4 6 7]]


# NUMPY BASIC 

In [15]:
import numpy as np
x = np.array([1,0,0,0,0,0,0,0,])

In [16]:
np.any(x)

True

In [17]:
np.all(x)

False

In [18]:
x = np.array([1,0, np.nan, np.inf])

In [20]:
np.isfinite(x)

array([ True,  True, False, False])

In [29]:
np.isnan(x)

array([False, False,  True, False])

In [30]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

In [32]:
b = np.iscomplex(a)

In [33]:
a[b]

array([1.+1.j, 0.+2.j])

In [38]:
c = np.isreal(a)

In [39]:
a[c]

array([1. +0.j, 4.5+0.j, 3. +0.j, 2. +0.j])

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [46]:
np.arange(30,70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [47]:
np.arange(30,70,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [49]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.random.normal(0,1)

0.007878830042070118

In [55]:
np.random.normal(0,1,15)

array([-1.06464763,  0.15470427, -0.40989038, -1.26101383, -0.1849695 ,
       -0.22831081, -0.69932196, -0.80282238, -0.73456373, -1.67561098,
        0.08145867, -0.06244647, -0.91873943,  0.61424203,  0.98467532])

In [58]:
v = np.arange(15,55)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [61]:
a = np.arange(10,22).reshape((3,4))

In [63]:
for i in np.nditer(a):
    print(i, end = ' ')

10 11 12 13 14 15 16 17 18 19 20 21 

In [66]:
np.linspace(10,49,5)

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [71]:
a = np.arange(21)
a[(a>=9) & (a<=15)] *= -1

In [72]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [74]:
x = np.random.randint(0,11,5)

In [75]:
x

array([3, 0, 1, 2, 5])

In [81]:
x = np.array([1,8,3,5])

In [82]:
y = np.random.randint(0,11,4)

In [83]:
x*y

array([ 6, 56,  9, 15])

In [86]:
a = np.arange(10,22).reshape((3,4))

In [88]:
a.shape

(3, 4)

In [97]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [99]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
x = np.zeros((10,10))
x[1:-1,1:-1] = 1
x[2:-2,2:-2] = 2
x[3:-3,3:-3] = 3
x[4:-4,4:-4] = 4
x[5:-5,5:-5] = 5

In [119]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 4., 4., 3., 2., 1., 0.],
       [0., 1., 2., 3., 4., 4., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [2]:
import numpy as np
l = np.diag([1,2,3,4,5])
print(l)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [148]:
x = np.zeros((4,4))
x[::2,::2] = 1
x[1::2,1::2] = 1


In [149]:
x

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [155]:
x = np.array([[0,1],[2,3]])
x

array([[0, 1],
       [2, 3]])

In [159]:
np.sum(x)


6

In [160]:
np.sum(x, axis = 0 )


array([2, 4])

In [161]:
np.sum(x, axis = 1)

array([1, 5])

In [166]:
x = np.array([4,5])
y = np.array([7,10])
np.dot(x,y)

78

In [169]:
a = np.array([[1, 2], [3, 4]])

In [173]:
a.tolist()

[[1, 2], [3, 4]]

In [174]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [181]:
a[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [2]:
np.array([12.23, 13.32, 100, 36.32])

array([ 12.23,  13.32, 100.  ,  36.32])

In [13]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
a = np.array([ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a[6] = 11

In [19]:
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [23]:
a = np.arange(12,39)

In [29]:
np.asfarray(a)

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.,
       38.])

In [33]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0

In [37]:
a[0:,0:] = 0

In [38]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
b = np.ones((3,3))
b = np.pad(b, pad_width = 1, constant_values = 5)
b

array([[5., 5., 5., 5., 5.],
       [5., 1., 1., 1., 5.],
       [5., 1., 1., 1., 5.],
       [5., 1., 1., 1., 5.],
       [5., 5., 5., 5., 5.]])

In [66]:
x = np.zeros((8,8), dtype = int)
x[::2,::2] = 1
x[1::2,1::2] = 1
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [70]:
y = np.zeros((8,8), dtype = int)
y[::2,::2] = 1
y[1::2,1::2] = 1
y

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [72]:
t = [1, 2, 3, 4, 5, 6, 7, 8]
np.asarray(t)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
x =  ([8, 4, 6], [1, 2, 3])
np.asarray(x)

array([[8, 4, 6],
       [1, 2, 3]])

In [83]:
t = [1, 2, 3, 4, 5, 6, 7, 8]
a = np.array(t)
b = np.array([[20,30,40],[50,60,70]])
np.append(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 20, 30, 40, 50, 60, 70])

In [86]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])
np.concatenate((a,b), axis = 1)

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [87]:
np.empty((3,6))

array([[1.37805232e-311, 5.13828272e-322, 0.00000000e+000,
        0.00000000e+000, 3.33773301e-307, 1.16095484e-028],
       [5.28595592e-085, 1.20480715e+132, 9.06192096e-096,
        1.09972302e-152, 1.96088859e+243, 1.47234459e-052],
       [5.56662000e+141, 2.13395513e+233, 8.17132964e+164,
        6.48224638e+170, 3.67145870e+228, 1.29136533e+295]])

In [88]:
np.full((2,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [89]:
c = np.array([0, 12, 45.21 ,34, 99.91])
f = (9*c +(32*5))/5
f


array([ 32.   ,  53.6  , 113.378,  93.2  , 211.838])

In [90]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [92]:
x = np.sqrt([1+0j])
x.real

array([1.])

In [93]:
x.imag

array([0.])

In [95]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = [0, 40]
np.in1d(array1,array2)

array([ True, False, False,  True, False])

In [105]:
a = np.array([0, 10, 20, 40, 20,10])
np.unique(a)

array([ 0, 10, 20, 40])

In [3]:
import numpy as np
a = np.array([0, 10, 20, 40, 60, 80])
b = [10, 30, 40, 50, 70]
np.setxor1d(a,b)

array([ 0, 20, 30, 50, 60, 70, 80])

In [7]:
a = [1,2,3,4]
x = np.tile(a,2)
x

array([1, 2, 3, 4, 1, 2, 3, 4])

In [8]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [10]:
b = [[1,2],[3,4]]
np.repeat(b,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [13]:
a = np.array([1, 2])
b = np.array([4, 5])
np.greater(a,b)


array([False, False])

In [14]:
np.greater_equal(a,b)

array([False, False])

In [15]:
np.less(a,b)

array([ True,  True])

In [16]:
np.less_equal(a,b)

array([ True,  True])

In [21]:
a = np.array([[4, 6],[2, 1]])
np.sort(a, axis = 1)

array([[4, 6],
       [1, 2]])

In [22]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
np.lexsort((first_names,last_names))

array([1, 3, 2, 4, 0], dtype=int64)

In [23]:
x = np.array([[0, 10, 20], [20, 30, 40]])
x[x>10]

array([20, 20, 30, 40])

In [24]:
np.nonzero(x>10)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [25]:
import numpy as np
a = np.arange(1.0, 2.0, 36.2)
np.savetxt('file.out', a, delimiter=',')

In [4]:
import numpy as np
x = np.arange(6)
np.full_like(x,10)

array([10, 10, 10, 10, 10, 10])

In [6]:
np.diagflat([4, 5, 6, 8,8])

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 8]])

In [7]:
np.linspace(2, 6, 30)

array([2.        , 2.13793103, 2.27586207, 2.4137931 , 2.55172414,
       2.68965517, 2.82758621, 2.96551724, 3.10344828, 3.24137931,
       3.37931034, 3.51724138, 3.65517241, 3.79310345, 3.93103448,
       4.06896552, 4.20689655, 4.34482759, 4.48275862, 4.62068966,
       4.75862069, 4.89655172, 5.03448276, 5.17241379, 5.31034483,
       5.44827586, 5.5862069 , 5.72413793, 5.86206897, 6.        ])

In [10]:
np.logspace(2., 5., 2)

array([   100., 100000.])

In [12]:
np.logspace(2., 5., 20, endpoint=True)

array([   100.        ,    143.84498883,    206.91380811,    297.63514416,
          428.13323987,    615.84821107,    885.86679041,   1274.2749857 ,
         1832.98071083,   2636.65089873,   3792.69019073,   5455.59478117,
         7847.59970351,  11288.37891685,  16237.76739189,  23357.2146909 ,
        33598.18286284,  48329.30238572,  69519.27961776, 100000.        ])

In [20]:
np.tri(4, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [25]:
 np.triu(np.arange(2, 14).reshape(3,4), 1)

array([[ 0,  3,  4,  5],
       [ 0,  0,  8,  9],
       [ 0,  0,  0, 13]])

In [30]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
x.flat[5]

10